import { Geologica, Dosis } from 'next/font/google'
import { ContextProvider } from '@/context'
import { Layout } from '@/components/layout'

import './globals.css'
import '@splidejs/react-splide/css/skyblue';

const geo = Geologica({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-geologica',
})
 
const dos = Dosis({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dosis',
})
 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${geo.variable} ${dos.variable}`}>
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
      </body>
    </html>
  )
}
