import { Geologica } from 'next/font/google'
import { ContextProvider } from '@/context'
import { Layout } from '@/components/layout'

import './globals.css'
const inter = Geologica({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${inter.className}`}>
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
      </body>
    </html>
  )
}
