import { Analytics } from '@vercel/analytics/react'
import { Geologica, Dosis } from 'next/font/google'
import { Layout } from '@/components/layout'
import { ContextProvider } from '@/context'

import './globals.css'
import 'react-multi-carousel/lib/styles.css'
import 'react-slideshow-image/dist/styles.css'
import 'react-toastify/dist/ReactToastify.css'

const geo = Geologica({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-geologica'
})

const dos = Dosis({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dosis'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${geo.variable} ${dos.variable}`}>
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
        <Analytics />
      </body>
    </html>
  )
}
